asyncapi: 2.6.0
info:
  title: Product audits API 6
  version: '1.0.0'
channels:
  place-order:
    publish:
      operationId: placeOrder
      message:
        $ref: "#/components/messages/OrderRequest"
  process-order:
    subscribe:
      operationId: processOrder
      message:
        $ref: "#/components/messages/Order"

components:
  messages:
    OrderRequest:
      name: OrderRequest
      title: An order request
      contentType: application/json
      payload:
        type: object
        required:
          - id
          - orderItems
        properties:
          id:
            description: Unique identifier of the order request
            type: number
          orderItems:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                quantity:
                  type: integer
                price:
                  type: number
              required:
                - id
                - name
                - quantity
                - price
      headers:
        type: object
        properties:
          SOURCE_ID:
            type: string
      examples:
        - name: NEW_ORDER_1
          payload:
            id: 12345
            orderItems:
              - id: 1
                name: "Macbook"
                quantity: 1
                price: 2000.00
              - id: 2
                name: "Iphone"
                quantity: 1
                price: 1000.00
          headers:
            SOURCE_ID: "CART_SERVICE"
        - name: NEW_ORDER_2
          payload:
            id: 67890
            orderItems:
              - id: 1
                name: "Vision Pro"
                quantity: 1
                price: 5000.00
              - id: 2
                name: "AirPods"
                quantity: 1
                price: 200.00
          headers:
            SOURCE_ID: "CART_SERVICE"
    Order:
      name: ProcessedOrder
      title: A processed order
      contentType: application/json
      payload:
        type: object
        required:
          - totalPrice
          - status
        properties:
          orderRequestId:
            type: integer
          totalAmount:
            type: number
          status:
            type: string
            enum:
              - PROCESSED
              - CANCELLED
      headers:
        type: object
        properties:
          SOURCE_ID:
            type: string
      examples:
        - name: NEW_ORDER_1
          payload:
            totalAmount: 3000.00
            status: "PROCESSED"
          headers:
            SOURCE_ID: "ORDER_SERVICE"
        - name: NEW_ORDER_2
          payload:
            totalAmount: 5200.00
            status: "PROCESSED"
          headers:
            SOURCE_ID: "ORDER_SERVICE"

